image: ubuntu:20.04

install:
- sudo apt-get update
- sudo apt-get install -y build-essential cmake git autoconf libboost-all-dev libopencv-dev libgflags-dev
- sudo apt-get install -y libopenblas-dev libprotobuf-dev libleveldb-dev libsnappy-dev libhdf5-serial-dev
- sudo apt-get install -y protobuf-compiler liblmdb-dev libgoogle-glog-dev libeigen3-dev

workspace: /shit/master-1

command: |
cd shit/master-1
./ci/build.sh

github:
prebuilds:
addBadge: false
addCheck: true
addComment: true
addLabel: gitpod-ready
addSummary: true
branches: true
master: true
pullRequests: true
